---
- hosts: all
  become: true
  serial: 1
  vars:
    wait_seconds: 3
  tasks:
    - name: ensure nginx is at the latest version
      apt:
          name: nginx
          state: latest
          force: yes

    - name: start nginx
      service:
          name: nginx
          state: restarted


    - name: pause for {{ wait_seconds | int }} second(s)
      ansible.builtin.pause:
        seconds: "{{ wait_seconds | int }}"
    - name: message
      ansible.builtin.debug:
        msg: "The end"

