---
- hosts: all
  become: true
  tasks:
    - name: ensure nginx is at the latest version
      apt:
          name: nginx
          state: present
          force: yes

    - name: start nginx
      service:
          name: nginx
          state: restarted



